sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"

script:
  - npm run test
  - npm run lint